kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-nodejs
          # image: nodejs-image:latest
          image: docker.io/aandrienko/tekton-api
          # image: docker.io/aandrienko/api
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
selector:
  app: nodejs-app
---
apiVersion: v1
data:
  config: |-
    DB_USER=
    DB_PASSWORD=
    DB_HOST=
    DB_PORT=5432
    DB_NAME=
    DB_SSLMODE=disable
    DB_ENABLE_AUTO_MIGRATION=true
    GRPC_PORT=50051
    REST_PORT=8080
    PROMETHEUS_PORT=9090
    TLS_HOSTNAME_OVERRIDE=
    TLS_PATH=/etc/tls
    NO_AUTH=false
    LOG_LEVEL=info
    LOGS_API=false
    LOGS_TYPE=File
    LOGS_BUFFER_SIZE=32768
    LOGS_PATH=/logs
    S3_BUCKET_NAME=
    S3_ENDPOINT=
    S3_HOSTNAME_IMMUTABLE=false
    S3_REGION=
    S3_ACCESS_KEY_ID=
    S3_SECRET_ACCESS_KEY=
    S3_MULTI_PART_SIZE=5242880
kind: ConfigMap
metadata:
  name: api-config
  namespace: tekton-pipelines